#!/usr/bin/perl
#
# A simple PERL script to decode CheckPoint DataCenter JSON file
#
# by HristoGrigorov@CheckMates
#

use v5.10;
use Getopt::Std;
use JSON::PP;

# Declare global vars
my $JSON_FILE;
my $OBJECT_NAME;
my $OBJECT_DESC;
my $OBJECT_ID;
my $OBJECT_RANGE;

our ($opt_c, $opt_h, $opt_f, $opt_n, $opt_d, $opt_i, $opt_r);

# Parse command line
getopts('chf:n:d:i:r:');

say "\nCheckPoint Generic DataCenter JSON file decoder by Hristo Grigorv\n";

# Help
if ($opt_h) {	
	say "Usage: deccpjson -f <path to JSON file> [-n <name>] [-d <descr>] [-i <id>] [-r <range>] [-h] [-c]\n\n";
	say "                 -f	path to JSON file";
	say "                 -n	search for object name";
	say "                 -d	search for object description";
	say "                 -i	search for object id";
	say "                 -r	search for object range";
	say "                 -c	check JSON structure only";
	say "                 -h	print usage info\n";
	exit 1;
}

# Filename
if ($opt_f) {
	if (! -f $opt_f) {
		say "error:unable to access $opt_f (check if file exists)";
		exit 1;
	}
	$JSON_FILE = $opt_f;
}

# Object Name
if ($opt_n) {
	say "Search for Object Name: $opt_n";
	$OBJECT_NAME = $opt_n;
}

# Object Descr
if ($opt_d) {
        say "Search for Object Description: $opt_d";
        $OBJECT_DESC = $opt_d;
}

# Object ID
if ($opt_i) {
        say "Search for Object ID: $opt_i";
        $OBJECT_ID = $opt_i;
}

# Object Range
if ($opt_r) {
        say "Search for Object Range: $opt_r";
        $OBJECT_RANGE = $opt_r;
}

# Store file content into internal variable
my $json_text = do {
   open(my $json_fh, "<:encoding(UTF-8)", $JSON_FILE)
      or die("Can't open \$JSON_FILE\": $!\n");
   local $/;
   <$json_fh>
};

# Decode JSON structure
my $json = JSON::PP->new->ascii->pretty->allow_nonref;
my $data = $json->decode($json_text);

# Quit if only checking file structure
if ($opt_c) {
	say "JSON file structure appears valid.\n";
	exit 1;
}

my $nobj = 0;
# Iterate and print
for ( @{$data->{objects}} ) 
{
	$nobj++;

	my $obj_name = $_->{name};
	my $obj_desc = $_->{description};
	my $obj_id = $_->{id};

	if ($OBJECT_NAME || $OBJECT_DESC || $OBJECT_ID) {

		my $is_match = 0;

		$is_match = 1 if ( $OBJECT_NAME && index(lc($obj_name), lc($OBJECT_NAME)) != -1);
		$is_match = 1 if ( $OBJECT_DESC && index(lc($obj_desc), lc($OBJECT_DESC)) != -1 );
		$is_match = 1 if ( $OBJECT_ID && index(lc($obj_id), lc($OBJECT_ID)) != -1 );

		next if (0 == $is_match);
	}

	if (!$OBJECT_RANGE) {
		say "";
		say "Object Name  : $obj_name";
		say "Object ID    : $obj_id";
		say "Object Desc  : $obj_desc";
	}

	my $cnt=1;
	for ( @{$_->{ranges}} ) {
		if ($OBJECT_RANGE) {
			if (index($_, $OBJECT_RANGE) != -1) {
				say "Found in object $obj_name as $_";
				next;
			}
		} else {
			say "[".$cnt++."]: $_";
		}
	}
}

say "\nFound total $nobj objects in file.\n";

# EOF
